apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: replicapool-single
  namespace: rook
spec:
  replicated:
    size: 1

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-block-single
provisioner: rook.io/block
parameters:
  pool: replicapool-single


